[package]
name = "google-integration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
google-authenticator = "0.4.2"
serde = "1.0.183"
serde_json = "1.0.104"
